all:  Electric.cpp Electric.hpp Flying.cpp Flying.hpp Water.cpp Water.hpp Fire.cpp Fire.hpp  main.cpp  Pokemon.cpp Pokemon.hpp Zapdos.cpp Zapdos.hpp Moltres.cpp Moltres.hpp Articuno.cpp Articuno.hpp

	c++ Electric.cpp Flying.cpp Water.cpp Fire.cpp main.cpp  Pokemon.cpp Zapdos.cpp Moltres.cpp Articuno.cpp
	./a.out
	

clean:
	rm -f  *.cpp~
	rm -f  *.hpp~
	rm -f  *.gch
	rm -f  *.out
